name: Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: setup gradle
      uses: gradle/gradle-build-action@v2
      
    - name: cache sonarcloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: decrypt keys
      run: . keys/decrypt-secrets.sh
      env:
        GPG_ENCRYPT_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: check code quality
      run: gradle check

    - name: upload code report to SonarCloud
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: gradle sonar
